# Generated by Django 6.0 on 2025-12-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.PositiveBigIntegerField(max_length=10)),
                ('service_type', models.CharField(max_length=10)),
                ('pickup_location', models.CharField(blank=True, max_length=250, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=250, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=250, null=True)),
                ('errand_destination', models.CharField(blank=True, max_length=250, null=True)),
                ('request_details', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
