# Generated by Django 6.0 on 2025-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0002_servicerequest_created_at_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
