# Generated by Django 6.0 on 2025-12-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0003_servicerequest_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at']},
        ),
    ]
